--------------------Departamento----------------------
CREATE TABLE DEPARTAMENTO 
(
	IDDEP		NUMBER(4) 								,
	NOME		VARCHAR2(50)	NOT NULL				,
	LOCALIZACAO	VARCHAR2(50)							,
	ORCAMENTO	NUMBER(10,2)							,
	CONSTRAINT	DEP_ID_PK	PRIMARY KEY(IDDEP)			,
	CONSTRAINT	DEP_ORCA_CHK	CHECK(ORCAMENTO > 0)
);
--------------------Funcionario-------------------------
CREATE TABLE FUNCIONARIO	
(
	IDFUNC		NUMBER(5)								,
	NOME		VARCHAR2(60)	NOT NULL				,
	CARGO		VARCHAR2(40)							,
	SALARIO		NUMBER(10,2)							,
	DATAADM		DATE			NOT NULL				,
	IDDEP		NUMBER(4)								,
	STATUS		CHAR(1)	DEFAULT 'A'						,
	CONSTRAINT	FUNC_IDFUNC_PK	PRIMARY KEY	(IDFUNC)	,
	CONSTRAINT	FUNC_SALARIO_CHK	CHECK(SALARIO > 0)	,
	CONSTRAINT	CHK_STATUS	CHECK (STATUS IN ('A','I'))	,
	CONSTRAINT 	FUNC_IDDEP_FK	FOREIGN KEY (IDDEP)
			REFERENCES	DEPARTAMENTO(IDDEP)
);
-------------------Projeto--------------------------------
CREATE TABLE PROJETO	
(
	IDPROJ		NUMBER(5)								,
	NOMEPROJ	VARCHAR2(60)	NOT NULL				,
	DATAINICIO	DATE									,
	DATAFIM		DATE									,
	IDDEP		NUMBER(4)								,
	CONSTRAINT	PROJ_IDPROJ_PK	PRIMARY KEY(IDPROJ)		,
	CONSTRAINT	PROJ_IDDEP_FK	FOREIGN KEY	(IDDEP)		
			REFERENCES DEPARTAMENTO	(IDDEP)
);